FROM haproxy:2.8-alpine

# Copy the HAProxy configuration
COPY haproxy2.cfg /usr/local/etc/haproxy/haproxy.cfg

# Copy certificates
COPY certs/app2/combined.pem /etc/haproxy/certs/combined.pem

# Expose HTTPS port
EXPOSE 8443

# Run HAProxy
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-d"]
